/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Client {
  'id' : bigint,
  'owner' : Principal,
  'name' : string,
  'email' : string,
  'notes' : string,
  'phone' : string,
}
export interface Payment {
  'id' : bigint,
  'method' : string,
  'clientId' : bigint,
  'owner' : Principal,
  'date' : Time,
  'notes' : string,
  'amount' : number,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  'addClient' : ActorMethod<[string, string, string, string], bigint>,
  'addPayment' : ActorMethod<[bigint, number, Time, string, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteClient' : ActorMethod<[bigint], undefined>,
  'deletePayment' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClient' : ActorMethod<[bigint], [] | [Client]>,
  'getClients' : ActorMethod<[], Array<Client>>,
  'getOverallPaymentTotal' : ActorMethod<[], number>,
  'getPayment' : ActorMethod<[bigint], [] | [Payment]>,
  'getPaymentTotalsByClient' : ActorMethod<[bigint], number>,
  'getPaymentsByClient' : ActorMethod<[bigint], Array<Payment>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchClients' : ActorMethod<[string], Array<Client>>,
  'searchPayments' : ActorMethod<[string], Array<Payment>>,
  'updateClient' : ActorMethod<
    [bigint, string, string, string, string],
    undefined
  >,
  'updatePayment' : ActorMethod<
    [bigint, number, Time, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];