/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Client = IDL.Record({
  'id' : IDL.Nat,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
});
export const Payment = IDL.Record({
  'id' : IDL.Nat,
  'method' : IDL.Text,
  'clientId' : IDL.Nat,
  'owner' : IDL.Principal,
  'date' : Time,
  'notes' : IDL.Text,
  'amount' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addClient' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addPayment' : IDL.Func(
      [IDL.Nat, IDL.Float64, Time, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteClient' : IDL.Func([IDL.Nat], [], []),
  'deletePayment' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClient' : IDL.Func([IDL.Nat], [IDL.Opt(Client)], ['query']),
  'getClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
  'getOverallPaymentTotal' : IDL.Func([], [IDL.Float64], ['query']),
  'getPayment' : IDL.Func([IDL.Nat], [IDL.Opt(Payment)], ['query']),
  'getPaymentTotalsByClient' : IDL.Func([IDL.Nat], [IDL.Float64], ['query']),
  'getPaymentsByClient' : IDL.Func([IDL.Nat], [IDL.Vec(Payment)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchClients' : IDL.Func([IDL.Text], [IDL.Vec(Client)], ['query']),
  'searchPayments' : IDL.Func([IDL.Text], [IDL.Vec(Payment)], ['query']),
  'updateClient' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updatePayment' : IDL.Func(
      [IDL.Nat, IDL.Float64, Time, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Client = IDL.Record({
    'id' : IDL.Nat,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Payment = IDL.Record({
    'id' : IDL.Nat,
    'method' : IDL.Text,
    'clientId' : IDL.Nat,
    'owner' : IDL.Principal,
    'date' : Time,
    'notes' : IDL.Text,
    'amount' : IDL.Float64,
  });
  
  return IDL.Service({
    'addClient' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addPayment' : IDL.Func(
        [IDL.Nat, IDL.Float64, Time, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteClient' : IDL.Func([IDL.Nat], [], []),
    'deletePayment' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClient' : IDL.Func([IDL.Nat], [IDL.Opt(Client)], ['query']),
    'getClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
    'getOverallPaymentTotal' : IDL.Func([], [IDL.Float64], ['query']),
    'getPayment' : IDL.Func([IDL.Nat], [IDL.Opt(Payment)], ['query']),
    'getPaymentTotalsByClient' : IDL.Func([IDL.Nat], [IDL.Float64], ['query']),
    'getPaymentsByClient' : IDL.Func([IDL.Nat], [IDL.Vec(Payment)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchClients' : IDL.Func([IDL.Text], [IDL.Vec(Client)], ['query']),
    'searchPayments' : IDL.Func([IDL.Text], [IDL.Vec(Payment)], ['query']),
    'updateClient' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updatePayment' : IDL.Func(
        [IDL.Nat, IDL.Float64, Time, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };